project_id = "qducanwbpleoceynmend"

[functions.admin-write]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.fetch-whatsapp-profile]
verify_jwt = false

[functions.process-schedules]
verify_jwt = false

[functions.download-whatsapp-media]
verify_jwt = false

[functions.execute-flow]
verify_jwt = false

[functions.update-lid-contacts]
verify_jwt = false

[functions.sync-contacts]
verify_jwt = false

[functions.google-auth]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.merge-duplicate-contacts]
verify_jwt = false

[functions.check-connections]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.execute-campaign]
verify_jwt = false

[functions.resolve-lid-contact]
verify_jwt = false

[functions.update-user-email]
verify_jwt = false

[functions.meta-api-webhook]
verify_jwt = false

[functions.send-meta-message]
verify_jwt = false

[functions.baileys-instance]
verify_jwt = false

[functions.baileys-webhook]
verify_jwt = false

[functions.baileys-create-session]
verify_jwt = false

[functions.save-system-setting]
verify_jwt = false

[functions.bulk-delete-contacts]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false
