project_id = "qducanwbpleoceynmend"

[functions.create-user]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.evolution-instance]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.fetch-whatsapp-profile]
verify_jwt = false

[functions.process-schedules]
verify_jwt = false

[functions.download-whatsapp-media]
verify_jwt = false

[functions.execute-flow]
verify_jwt = false

[functions.update-lid-contacts]
verify_jwt = false

[functions.sync-contacts]
verify_jwt = false

[functions.google-auth]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.merge-duplicate-contacts]
verify_jwt = false
